/*
    Rsero is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Rsero is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Rsero.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
#ifndef USE_STANC3
#define USE_STANC3
#endif
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_independent_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 140> locations_array__ =
  {" (found before start of program)",
  " (in 'independent', line 28, column 2 to column 33)",
  " (in 'independent', line 29, column 2 to column 34)",
  " (in 'independent', line 30, column 2 to column 46)",
  " (in 'independent', line 33, column 2 to column 12)",
  " (in 'independent', line 34, column 2 to column 9)",
  " (in 'independent', line 35, column 2 to column 53)",
  " (in 'independent', line 36, column 2 to column 52)",
  " (in 'independent', line 37, column 2 to column 36)",
  " (in 'independent', line 38, column 2 to column 41)",
  " (in 'independent', line 39, column 2 to column 9)",
  " (in 'independent', line 41, column 2 to column 6)",
  " (in 'independent', line 48, column 6 to column 12)",
  " (in 'independent', line 51, column 8 to column 48)",
  " (in 'independent', line 50, column 33 to line 52, column 9)",
  " (in 'independent', line 50, column 8 to line 52, column 9)",
  " (in 'independent', line 49, column 32 to line 53, column 7)",
  " (in 'independent', line 49, column 6 to line 53, column 7)",
  " (in 'independent', line 54, column 6 to column 27)",
  " (in 'independent', line 47, column 25 to line 55, column 5)",
  " (in 'independent', line 47, column 4 to line 55, column 5)",
  " (in 'independent', line 46, column 7 to line 56, column 3)",
  " (in 'independent', line 44, column 6 to column 21)",
  " (in 'independent', line 43, column 25 to line 45, column 5)",
  " (in 'independent', line 43, column 4 to line 45, column 5)",
  " (in 'independent', line 42, column 17 to line 46, column 3)",
  " (in 'independent', line 42, column 2 to line 56, column 3)",
  " (in 'independent', line 58, column 2 to column 6)",
  " (in 'independent', line 62, column 8 to column 48)",
  " (in 'independent', line 65, column 10 to column 17)",
  " (in 'independent', line 69, column 12 to column 65)",
  " (in 'independent', line 68, column 15 to line 70, column 11)",
  " (in 'independent', line 67, column 12 to column 54)",
  " (in 'independent', line 66, column 30 to line 68, column 11)",
  " (in 'independent', line 66, column 10 to line 70, column 11)",
  " (in 'independent', line 63, column 23 to line 71, column 9)",
  " (in 'independent', line 63, column 8 to line 71, column 9)",
  " (in 'independent', line 72, column 8 to column 15)",
  " (in 'independent', line 61, column 27 to line 73, column 7)",
  " (in 'independent', line 61, column 6 to line 73, column 7)",
  " (in 'independent', line 60, column 26 to line 74, column 5)",
  " (in 'independent', line 60, column 4 to line 74, column 5)",
  " (in 'independent', line 59, column 22 to line 75, column 3)",
  " (in 'independent', line 59, column 2 to line 75, column 3)",
  " (in 'independent', line 79, column 8 to column 16)",
  " (in 'independent', line 81, column 10 to column 45)",
  " (in 'independent', line 80, column 21 to line 82, column 9)",
  " (in 'independent', line 80, column 8 to line 82, column 9)",
  " (in 'independent', line 86, column 10 to column 46)",
  " (in 'independent', line 87, column 10 to column 49)",
  " (in 'independent', line 90, column 14 to column 41)",
  " (in 'independent', line 91, column 14 to column 82)",
  " (in 'independent', line 89, column 25 to line 92, column 13)",
  " (in 'independent', line 89, column 12 to line 92, column 13)",
  " (in 'independent', line 88, column 18 to line 93, column 11)",
  " (in 'independent', line 88, column 10 to line 93, column 11)",
  " (in 'independent', line 94, column 10 to column 41)",
  " (in 'independent', line 84, column 21 to line 96, column 9)",
  " (in 'independent', line 84, column 8 to line 96, column 9)",
  " (in 'independent', line 78, column 27 to line 97, column 7)",
  " (in 'independent', line 78, column 6 to line 97, column 7)",
  " (in 'independent', line 77, column 26 to line 98, column 5)",
  " (in 'independent', line 77, column 4 to line 98, column 5)",
  " (in 'independent', line 76, column 22 to line 99, column 3)",
  " (in 'independent', line 76, column 2 to line 99, column 3)",
  " (in 'independent', line 104, column 8 to column 19)",
  " (in 'independent', line 106, column 10 to column 41)",
  " (in 'independent', line 105, column 41 to line 107, column 9)",
  " (in 'independent', line 105, column 8 to line 107, column 9)",
  " (in 'independent', line 108, column 8 to column 56)",
  " (in 'independent', line 103, column 19 to line 109, column 7)",
  " (in 'independent', line 103, column 6 to line 109, column 7)",
  " (in 'independent', line 102, column 25 to line 110, column 5)",
  " (in 'independent', line 102, column 4 to line 110, column 5)",
  " (in 'independent', line 101, column 24 to line 111, column 3)",
  " (in 'independent', line 101, column 2 to line 111, column 3)",
  " (in 'independent', line 115, column 4 to column 72)",
  " (in 'independent', line 113, column 15 to line 116, column 3)",
  " (in 'independent', line 113, column 2 to line 116, column 3)",
  " (in 'independent', line 121, column 4 to column 41)",
  " (in 'independent', line 120, column 23 to line 122, column 3)",
  " (in 'independent', line 120, column 2 to line 122, column 3)",
  " (in 'independent', line 126, column 6 to column 38)",
  " (in 'independent', line 125, column 28 to line 127, column 5)",
  " (in 'independent', line 125, column 4 to line 127, column 5)",
  " (in 'independent', line 124, column 28 to line 128, column 3)",
  " (in 'independent', line 124, column 2 to line 128, column 3)",
  " (in 'independent', line 129, column 2 to column 31)",
  " (in 'independent', line 132, column 4 to column 52)",
  " (in 'independent', line 131, column 17 to line 133, column 3)",
  " (in 'independent', line 131, column 2 to line 133, column 3)",
  " (in 'independent', line 2, column 2 to column 18)",
  " (in 'independent', line 3, column 2 to column 28)",
  " (in 'independent', line 4, column 23 to column 24)",
  " (in 'independent', line 4, column 25 to column 35)",
  " (in 'independent', line 4, column 2 to column 37)",
  " (in 'independent', line 5, column 23 to column 24)",
  " (in 'independent', line 5, column 25 to column 35)",
  " (in 'independent', line 5, column 2 to column 37)",
  " (in 'independent', line 6, column 2 to column 24)",
  " (in 'independent', line 7, column 2 to column 18)",
  " (in 'independent', line 8, column 20 to column 21)",
  " (in 'independent', line 8, column 2 to column 23)",
  " (in 'independent', line 9, column 27 to column 28)",
  " (in 'independent', line 9, column 2 to column 30)",
  " (in 'independent', line 10, column 2 to column 40)",
  " (in 'independent', line 11, column 30 to column 31)",
  " (in 'independent', line 11, column 2 to column 33)",
  " (in 'independent', line 12, column 2 to column 26)",
  " (in 'independent', line 13, column 2 to column 31)",
  " (in 'independent', line 14, column 2 to column 28)",
  " (in 'independent', line 15, column 30 to column 39)",
  " (in 'independent', line 15, column 40 to column 54)",
  " (in 'independent', line 15, column 2 to column 56)",
  " (in 'independent', line 16, column 32 to column 33)",
  " (in 'independent', line 16, column 2 to column 35)",
  " (in 'independent', line 17, column 30 to column 31)",
  " (in 'independent', line 17, column 2 to column 33)",
  " (in 'independent', line 18, column 26 to column 27)",
  " (in 'independent', line 18, column 2 to column 30)",
  " (in 'independent', line 19, column 28 to column 38)",
  " (in 'independent', line 19, column 2 to column 40)",
  " (in 'independent', line 20, column 2 to column 27)",
  " (in 'independent', line 21, column 2 to column 27)",
  " (in 'independent', line 22, column 2 to column 28)",
  " (in 'independent', line 23, column 2 to column 29)",
  " (in 'independent', line 24, column 2 to column 29)",
  " (in 'independent', line 25, column 2 to column 29)",
  " (in 'independent', line 28, column 24 to column 31)",
  " (in 'independent', line 30, column 17 to column 29)",
  " (in 'independent', line 30, column 30 to column 44)",
  " (in 'independent', line 33, column 9 to column 10)",
  " (in 'independent', line 35, column 29 to column 30)",
  " (in 'independent', line 35, column 31 to column 41)",
  " (in 'independent', line 35, column 42 to column 51)",
  " (in 'independent', line 36, column 28 to column 29)",
  " (in 'independent', line 36, column 30 to column 40)",
  " (in 'independent', line 36, column 41 to column 50)",
  " (in 'independent', line 37, column 25 to column 34)",
  " (in 'independent', line 38, column 38 to column 39)"};
class model_independent final : public model_base_crtp<model_independent> {
private:
  int A;
  int NAgeGroups;
  std::vector<std::vector<int>> class1;
  std::vector<std::vector<int>> class2;
  int NGroups;
  int N;
  std::vector<int> age;
  std::vector<int> Y;
  int seroreversion;
  std::vector<int> categoryindex;
  int Ncategory;
  int Ncategoryclass;
  int maxNcategory;
  std::vector<std::vector<int>> MatrixCategory;
  std::vector<int> age_at_sampling;
  std::vector<int> sampling_year;
  std::vector<int> age_group;
  std::vector<int> age_at_init;
  double priorY1;
  double priorY2;
  double priorRho;
  double se;
  double sp;
  int cat_lambda;
public:
  ~model_independent() {}
  model_independent(stan::io::var_context& context__, unsigned int
                    random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_independent_namespace::model_independent";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 91;
      context__.validate_dims("data initialization", "A", "int",
        std::vector<size_t>{});
      A = std::numeric_limits<int>::min();
      current_statement__ = 91;
      A = context__.vals_i("A")[(1 - 1)];
      current_statement__ = 91;
      stan::math::check_greater_or_equal(function__, "A", A, 0);
      current_statement__ = 92;
      context__.validate_dims("data initialization", "NAgeGroups", "int",
        std::vector<size_t>{});
      NAgeGroups = std::numeric_limits<int>::min();
      current_statement__ = 92;
      NAgeGroups = context__.vals_i("NAgeGroups")[(1 - 1)];
      current_statement__ = 92;
      stan::math::check_greater_or_equal(function__, "NAgeGroups",
        NAgeGroups, 1);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("class1", "A", A);
      current_statement__ = 94;
      stan::math::validate_non_negative_index("class1", "NAgeGroups",
        NAgeGroups);
      current_statement__ = 95;
      context__.validate_dims("data initialization", "class1", "int",
        std::vector<size_t>{static_cast<size_t>(A),
          static_cast<size_t>(NAgeGroups)});
      class1 = std::vector<std::vector<int>>(A,
                 std::vector<int>(NAgeGroups,
                   std::numeric_limits<int>::min()));
      {
        std::vector<int> class1_flat__;
        current_statement__ = 95;
        class1_flat__ = context__.vals_i("class1");
        current_statement__ = 95;
        pos__ = 1;
        current_statement__ = 95;
        for (int sym1__ = 1; sym1__ <= NAgeGroups; ++sym1__) {
          current_statement__ = 95;
          for (int sym2__ = 1; sym2__ <= A; ++sym2__) {
            current_statement__ = 95;
            stan::model::assign(class1, class1_flat__[(pos__ - 1)],
              "assigning variable class1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 95;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 95;
      stan::math::check_greater_or_equal(function__, "class1", class1, 1);
      current_statement__ = 96;
      stan::math::validate_non_negative_index("class2", "A", A);
      current_statement__ = 97;
      stan::math::validate_non_negative_index("class2", "NAgeGroups",
        NAgeGroups);
      current_statement__ = 98;
      context__.validate_dims("data initialization", "class2", "int",
        std::vector<size_t>{static_cast<size_t>(A),
          static_cast<size_t>(NAgeGroups)});
      class2 = std::vector<std::vector<int>>(A,
                 std::vector<int>(NAgeGroups,
                   std::numeric_limits<int>::min()));
      {
        std::vector<int> class2_flat__;
        current_statement__ = 98;
        class2_flat__ = context__.vals_i("class2");
        current_statement__ = 98;
        pos__ = 1;
        current_statement__ = 98;
        for (int sym1__ = 1; sym1__ <= NAgeGroups; ++sym1__) {
          current_statement__ = 98;
          for (int sym2__ = 1; sym2__ <= A; ++sym2__) {
            current_statement__ = 98;
            stan::model::assign(class2, class2_flat__[(pos__ - 1)],
              "assigning variable class2", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 98;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 98;
      stan::math::check_greater_or_equal(function__, "class2", class2, 1);
      current_statement__ = 99;
      context__.validate_dims("data initialization", "NGroups", "int",
        std::vector<size_t>{});
      NGroups = std::numeric_limits<int>::min();
      current_statement__ = 99;
      NGroups = context__.vals_i("NGroups")[(1 - 1)];
      current_statement__ = 99;
      stan::math::check_greater_or_equal(function__, "NGroups", NGroups, 0);
      current_statement__ = 100;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 100;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 100;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 101;
      stan::math::validate_non_negative_index("age", "N", N);
      current_statement__ = 102;
      context__.validate_dims("data initialization", "age", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      age = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 102;
      age = context__.vals_i("age");
      current_statement__ = 102;
      stan::math::check_greater_or_equal(function__, "age", age, 0);
      current_statement__ = 103;
      stan::math::validate_non_negative_index("Y", "N", N);
      current_statement__ = 104;
      context__.validate_dims("data initialization", "Y", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      Y = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 104;
      Y = context__.vals_i("Y");
      current_statement__ = 104;
      stan::math::check_greater_or_equal(function__, "Y", Y, 0);
      current_statement__ = 104;
      stan::math::check_less_or_equal(function__, "Y", Y, 1);
      current_statement__ = 105;
      context__.validate_dims("data initialization", "seroreversion", "int",
        std::vector<size_t>{});
      seroreversion = std::numeric_limits<int>::min();
      current_statement__ = 105;
      seroreversion = context__.vals_i("seroreversion")[(1 - 1)];
      current_statement__ = 105;
      stan::math::check_greater_or_equal(function__, "seroreversion",
        seroreversion, 0);
      current_statement__ = 105;
      stan::math::check_less_or_equal(function__, "seroreversion",
        seroreversion, 1);
      current_statement__ = 106;
      stan::math::validate_non_negative_index("categoryindex", "N", N);
      current_statement__ = 107;
      context__.validate_dims("data initialization", "categoryindex", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      categoryindex = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 107;
      categoryindex = context__.vals_i("categoryindex");
      current_statement__ = 107;
      stan::math::check_greater_or_equal(function__, "categoryindex",
        categoryindex, 1);
      current_statement__ = 108;
      context__.validate_dims("data initialization", "Ncategory", "int",
        std::vector<size_t>{});
      Ncategory = std::numeric_limits<int>::min();
      current_statement__ = 108;
      Ncategory = context__.vals_i("Ncategory")[(1 - 1)];
      current_statement__ = 108;
      stan::math::check_greater_or_equal(function__, "Ncategory", Ncategory,
        1);
      current_statement__ = 109;
      context__.validate_dims("data initialization", "Ncategoryclass", "int",
        std::vector<size_t>{});
      Ncategoryclass = std::numeric_limits<int>::min();
      current_statement__ = 109;
      Ncategoryclass = context__.vals_i("Ncategoryclass")[(1 - 1)];
      current_statement__ = 109;
      stan::math::check_greater_or_equal(function__, "Ncategoryclass",
        Ncategoryclass, 1);
      current_statement__ = 110;
      context__.validate_dims("data initialization", "maxNcategory", "int",
        std::vector<size_t>{});
      maxNcategory = std::numeric_limits<int>::min();
      current_statement__ = 110;
      maxNcategory = context__.vals_i("maxNcategory")[(1 - 1)];
      current_statement__ = 110;
      stan::math::check_greater_or_equal(function__, "maxNcategory",
        maxNcategory, 1);
      current_statement__ = 111;
      stan::math::validate_non_negative_index("MatrixCategory", "Ncategory",
        Ncategory);
      current_statement__ = 112;
      stan::math::validate_non_negative_index("MatrixCategory",
        "Ncategoryclass", Ncategoryclass);
      current_statement__ = 113;
      context__.validate_dims("data initialization", "MatrixCategory", "int",
        std::vector<size_t>{static_cast<size_t>(Ncategory),
          static_cast<size_t>(Ncategoryclass)});
      MatrixCategory = std::vector<std::vector<int>>(Ncategory,
                         std::vector<int>(Ncategoryclass,
                           std::numeric_limits<int>::min()));
      {
        std::vector<int> MatrixCategory_flat__;
        current_statement__ = 113;
        MatrixCategory_flat__ = context__.vals_i("MatrixCategory");
        current_statement__ = 113;
        pos__ = 1;
        current_statement__ = 113;
        for (int sym1__ = 1; sym1__ <= Ncategoryclass; ++sym1__) {
          current_statement__ = 113;
          for (int sym2__ = 1; sym2__ <= Ncategory; ++sym2__) {
            current_statement__ = 113;
            stan::model::assign(MatrixCategory, MatrixCategory_flat__[(pos__
              - 1)], "assigning variable MatrixCategory",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 113;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 113;
      stan::math::check_greater_or_equal(function__, "MatrixCategory",
        MatrixCategory, 1);
      current_statement__ = 114;
      stan::math::validate_non_negative_index("age_at_sampling", "N", N);
      current_statement__ = 115;
      context__.validate_dims("data initialization", "age_at_sampling",
        "int", std::vector<size_t>{static_cast<size_t>(N)});
      age_at_sampling = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 115;
      age_at_sampling = context__.vals_i("age_at_sampling");
      current_statement__ = 115;
      stan::math::check_greater_or_equal(function__, "age_at_sampling",
        age_at_sampling, 0);
      current_statement__ = 116;
      stan::math::validate_non_negative_index("sampling_year", "N", N);
      current_statement__ = 117;
      context__.validate_dims("data initialization", "sampling_year", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      sampling_year = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 117;
      sampling_year = context__.vals_i("sampling_year");
      current_statement__ = 117;
      stan::math::check_greater_or_equal(function__, "sampling_year",
        sampling_year, 0);
      current_statement__ = 118;
      stan::math::validate_non_negative_index("age_group", "N", N);
      current_statement__ = 119;
      context__.validate_dims("data initialization", "age_group", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      age_group = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 119;
      age_group = context__.vals_i("age_group");
      current_statement__ = 119;
      stan::math::check_greater_or_equal(function__, "age_group", age_group,
        1);
      current_statement__ = 120;
      stan::math::validate_non_negative_index("age_at_init", "NAgeGroups",
        NAgeGroups);
      current_statement__ = 121;
      context__.validate_dims("data initialization", "age_at_init", "int",
        std::vector<size_t>{static_cast<size_t>(NAgeGroups)});
      age_at_init = std::vector<int>(NAgeGroups,
                      std::numeric_limits<int>::min());
      current_statement__ = 121;
      age_at_init = context__.vals_i("age_at_init");
      current_statement__ = 121;
      stan::math::check_greater_or_equal(function__, "age_at_init",
        age_at_init, 1);
      current_statement__ = 122;
      context__.validate_dims("data initialization", "priorY1", "double",
        std::vector<size_t>{});
      priorY1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 122;
      priorY1 = context__.vals_r("priorY1")[(1 - 1)];
      current_statement__ = 122;
      stan::math::check_greater_or_equal(function__, "priorY1", priorY1, 0);
      current_statement__ = 123;
      context__.validate_dims("data initialization", "priorY2", "double",
        std::vector<size_t>{});
      priorY2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 123;
      priorY2 = context__.vals_r("priorY2")[(1 - 1)];
      current_statement__ = 123;
      stan::math::check_greater_or_equal(function__, "priorY2", priorY2, 0);
      current_statement__ = 124;
      context__.validate_dims("data initialization", "priorRho", "double",
        std::vector<size_t>{});
      priorRho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 124;
      priorRho = context__.vals_r("priorRho")[(1 - 1)];
      current_statement__ = 124;
      stan::math::check_greater_or_equal(function__, "priorRho", priorRho, 0);
      current_statement__ = 125;
      context__.validate_dims("data initialization", "se", "double",
        std::vector<size_t>{});
      se = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 125;
      se = context__.vals_r("se")[(1 - 1)];
      current_statement__ = 125;
      stan::math::check_greater_or_equal(function__, "se", se, 0);
      current_statement__ = 125;
      stan::math::check_less_or_equal(function__, "se", se, 1);
      current_statement__ = 126;
      context__.validate_dims("data initialization", "sp", "double",
        std::vector<size_t>{});
      sp = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 126;
      sp = context__.vals_r("sp")[(1 - 1)];
      current_statement__ = 126;
      stan::math::check_greater_or_equal(function__, "sp", sp, 0);
      current_statement__ = 126;
      stan::math::check_less_or_equal(function__, "sp", sp, 1);
      current_statement__ = 127;
      context__.validate_dims("data initialization", "cat_lambda", "int",
        std::vector<size_t>{});
      cat_lambda = std::numeric_limits<int>::min();
      current_statement__ = 127;
      cat_lambda = context__.vals_i("cat_lambda")[(1 - 1)];
      current_statement__ = 127;
      stan::math::check_greater_or_equal(function__, "cat_lambda",
        cat_lambda, 0);
      current_statement__ = 128;
      stan::math::validate_non_negative_index("lambda", "NGroups", NGroups);
      current_statement__ = 129;
      stan::math::validate_non_negative_index("Flambda2", "maxNcategory",
        maxNcategory);
      current_statement__ = 130;
      stan::math::validate_non_negative_index("Flambda2", "Ncategoryclass",
        Ncategoryclass);
      current_statement__ = 131;
      stan::math::validate_non_negative_index("x", "A", A);
      current_statement__ = 132;
      stan::math::validate_non_negative_index("P1", "A", A);
      current_statement__ = 133;
      stan::math::validate_non_negative_index("P1", "NAgeGroups", NAgeGroups);
      current_statement__ = 134;
      stan::math::validate_non_negative_index("P1", "Ncategory", Ncategory);
      current_statement__ = 135;
      stan::math::validate_non_negative_index("P", "A", A);
      current_statement__ = 136;
      stan::math::validate_non_negative_index("P", "NAgeGroups", NAgeGroups);
      current_statement__ = 137;
      stan::math::validate_non_negative_index("P", "Ncategory", Ncategory);
      current_statement__ = 138;
      stan::math::validate_non_negative_index("Flambda", "Ncategory",
        Ncategory);
      current_statement__ = 139;
      stan::math::validate_non_negative_index("Likelihood", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = NGroups + 1 + (maxNcategory * Ncategoryclass);
  }
  inline std::string model_name() const final {
    return "model_independent";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_independent_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<local_scalar_t__> lambda =
        std::vector<local_scalar_t__>(NGroups, DUMMY_VAR__);
      current_statement__ = 1;
      lambda = in__.template read_constrain_lb<std::vector<local_scalar_t__>,
                 jacobian__>(0, lp__, NGroups);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 2;
      rho = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              20, lp__);
      std::vector<std::vector<local_scalar_t__>> Flambda2 =
        std::vector<std::vector<local_scalar_t__>>(maxNcategory,
          std::vector<local_scalar_t__>(Ncategoryclass, DUMMY_VAR__));
      current_statement__ = 3;
      Flambda2 = in__.template read<
                   std::vector<std::vector<local_scalar_t__>>>(maxNcategory,
                   Ncategoryclass);
      std::vector<local_scalar_t__> x =
        std::vector<local_scalar_t__>(A, DUMMY_VAR__);
      local_scalar_t__ L = DUMMY_VAR__;
      std::vector<std::vector<std::vector<local_scalar_t__>>> P1 =
        std::vector<std::vector<std::vector<local_scalar_t__>>>(A,
          std::vector<std::vector<local_scalar_t__>>(NAgeGroups,
            std::vector<local_scalar_t__>(Ncategory, DUMMY_VAR__)));
      std::vector<std::vector<std::vector<local_scalar_t__>>> P =
        std::vector<std::vector<std::vector<local_scalar_t__>>>(A,
          std::vector<std::vector<local_scalar_t__>>(NAgeGroups,
            std::vector<local_scalar_t__>(Ncategory, DUMMY_VAR__)));
      std::vector<local_scalar_t__> Flambda =
        std::vector<local_scalar_t__>(Ncategory, DUMMY_VAR__);
      std::vector<local_scalar_t__> Likelihood =
        std::vector<local_scalar_t__>(N, DUMMY_VAR__);
      local_scalar_t__ c = DUMMY_VAR__;
      current_statement__ = 11;
      c = 0;
      current_statement__ = 26;
      if (stan::math::logical_negation(cat_lambda)) {
        current_statement__ = 24;
        for (int i = 1; i <= Ncategory; ++i) {
          current_statement__ = 22;
          stan::model::assign(Flambda, 1, "assigning variable Flambda",
            stan::model::index_uni(i));
        }
      } else {
        current_statement__ = 20;
        for (int i = 1; i <= Ncategory; ++i) {
          current_statement__ = 12;
          c = 0;
          current_statement__ = 17;
          for (int I = 1; I <= Ncategoryclass; ++I) {
            current_statement__ = 15;
            if (stan::math::logical_gt(
                  stan::model::rvalue(MatrixCategory, "MatrixCategory",
                    stan::model::index_uni(i), stan::model::index_uni(I)), 1)) {
              current_statement__ = 13;
              c = (c +
                stan::model::rvalue(Flambda2, "Flambda2",
                  stan::model::index_uni(
                    stan::model::rvalue(MatrixCategory, "MatrixCategory",
                      stan::model::index_uni(i), stan::model::index_uni(I))),
                  stan::model::index_uni(I)));
            }
          }
          current_statement__ = 18;
          stan::model::assign(Flambda, stan::math::exp(c),
            "assigning variable Flambda", stan::model::index_uni(i));
        }
      }
      current_statement__ = 27;
      L = 1;
      current_statement__ = 43;
      if (stan::math::logical_eq(seroreversion, 0)) {
        current_statement__ = 41;
        for (int J = 1; J <= NAgeGroups; ++J) {
          current_statement__ = 39;
          for (int i = 1; i <= Ncategory; ++i) {
            current_statement__ = 28;
            stan::model::assign(P1,
              stan::math::exp(
                (-stan::model::rvalue(Flambda, "Flambda",
                    stan::model::index_uni(i)) *
                stan::model::rvalue(lambda, "lambda",
                  stan::model::index_uni(1)))), "assigning variable P1",
              stan::model::index_uni(1), stan::model::index_uni(J),
              stan::model::index_uni(i));
            current_statement__ = 36;
            for (int j = 1; j <= (A - 1); ++j) {
              current_statement__ = 29;
              stan::model::assign(x, 1, "assigning variable x",
                stan::model::index_uni(j));
              current_statement__ = 34;
              if (stan::math::logical_lt(j,
                    stan::model::rvalue(age_at_init, "age_at_init",
                      stan::model::index_uni(J)))) {
                current_statement__ = 32;
                stan::model::assign(P1,
                  stan::math::exp(
                    (-stan::model::rvalue(Flambda, "Flambda",
                        stan::model::index_uni(i)) *
                    stan::model::rvalue(lambda, "lambda",
                      stan::model::index_uni(j)))), "assigning variable P1",
                  stan::model::index_uni((j + 1)), stan::model::index_uni(J),
                  stan::model::index_uni(i));
              } else {
                current_statement__ = 30;
                stan::model::assign(P1,
                  (stan::model::rvalue(P1, "P1", stan::model::index_uni(j),
                     stan::model::index_uni(J), stan::model::index_uni(i)) *
                  stan::math::exp(
                    (-stan::model::rvalue(Flambda, "Flambda",
                        stan::model::index_uni(i)) *
                    stan::model::rvalue(lambda, "lambda",
                      stan::model::index_uni((j + 1)))))),
                  "assigning variable P1", stan::model::index_uni((j + 1)),
                  stan::model::index_uni(J), stan::model::index_uni(i));
              }
            }
            current_statement__ = 37;
            stan::model::assign(x, 1, "assigning variable x",
              stan::model::index_uni(A));
          }
        }
      }
      current_statement__ = 64;
      if (stan::math::logical_eq(seroreversion, 1)) {
        current_statement__ = 62;
        for (int J = 1; J <= NAgeGroups; ++J) {
          current_statement__ = 60;
          for (int i = 1; i <= Ncategory; ++i) {
            current_statement__ = 44;
            stan::model::assign(x, 1, "assigning variable x",
              stan::model::index_uni(A));
            current_statement__ = 47;
            for (int j = 1; j <= A; ++j) {
              current_statement__ = 45;
              stan::model::assign(x,
                stan::math::exp(
                  (-stan::model::rvalue(Flambda, "Flambda",
                      stan::model::index_uni(i)) *
                  stan::model::rvalue(lambda, "lambda",
                    stan::model::index_uni(1)))), "assigning variable x",
                stan::model::index_uni(j));
            }
            current_statement__ = 58;
            for (int j = 1; j <= A; ++j) {
              current_statement__ = 48;
              L = (stan::model::rvalue(Flambda, "Flambda",
                     stan::model::index_uni(i))
                *
                stan::model::rvalue(lambda, "lambda",
                  stan::model::index_uni(
                    stan::model::rvalue(age_at_init, "age_at_init",
                      stan::model::index_uni(J)))));
              current_statement__ = 49;
              stan::model::assign(x, ((rho / (L + rho)) + ((L / (L + rho)) *
                stan::math::exp(-L))), "assigning variable x",
                stan::model::index_uni(j));
              current_statement__ = 55;
              if (stan::math::logical_gt(j, 1)) {
                current_statement__ = 53;
                for (int k = 2; k <= j; ++k) {
                  current_statement__ = 50;
                  L = (stan::model::rvalue(Flambda, "Flambda",
                         stan::model::index_uni(i))
                    *
                    stan::model::rvalue(lambda, "lambda",
                      stan::model::index_uni(((j - k) + 2))));
                  current_statement__ = 51;
                  stan::model::assign(x,
                    ((stan::model::rvalue(x, "x",
                        stan::model::index_uni(((j - k) + 2))) *
                    stan::math::exp(-(rho + L))) + ((rho / (L + rho)) * (1 -
                    stan::math::exp(-(rho + L))))), "assigning variable x",
                    stan::model::index_uni((((j - k) + 2) - 1)));
                }
              }
              current_statement__ = 56;
              stan::model::assign(P1,
                stan::model::rvalue(x, "x",
                  stan::model::index_uni(
                    stan::model::rvalue(age_at_init, "age_at_init",
                      stan::model::index_uni(J)))), "assigning variable P1",
                stan::model::index_uni(j), stan::model::index_uni(J),
                stan::model::index_uni(i));
            }
          }
        }
      }
      current_statement__ = 75;
      for (int J = 1; J <= NAgeGroups; ++J) {
        current_statement__ = 73;
        for (int i = 1; i <= Ncategory; ++i) {
          current_statement__ = 71;
          for (int j = 1; j <= A; ++j) {
            current_statement__ = 65;
            stan::model::assign(P, 0, "assigning variable P",
              stan::model::index_uni(j), stan::model::index_uni(J),
              stan::model::index_uni(i));
            current_statement__ = 68;
            for (int k =
                   stan::model::rvalue(class1, "class1",
                     stan::model::index_uni(j), stan::model::index_uni(J)); k
                 <=
                 stan::model::rvalue(class2, "class2",
                   stan::model::index_uni(j), stan::model::index_uni(J)); ++k) {
              current_statement__ = 66;
              stan::model::assign(P,
                (stan::model::rvalue(P1, "P1", stan::model::index_uni(k),
                   stan::model::index_uni(J), stan::model::index_uni(i)) +
                stan::model::rvalue(P, "P", stan::model::index_uni(j),
                  stan::model::index_uni(J), stan::model::index_uni(i))),
                "assigning variable P", stan::model::index_uni(j),
                stan::model::index_uni(J), stan::model::index_uni(i));
            }
            current_statement__ = 69;
            stan::model::assign(P,
              (stan::model::rvalue(P, "P", stan::model::index_uni(j),
                 stan::model::index_uni(J), stan::model::index_uni(i)) /
              ((stan::model::rvalue(class2, "class2",
                  stan::model::index_uni(j), stan::model::index_uni(J)) -
              stan::model::rvalue(class1, "class1",
                stan::model::index_uni(j), stan::model::index_uni(J))) + 1)),
              "assigning variable P", stan::model::index_uni(j),
              stan::model::index_uni(J), stan::model::index_uni(i));
          }
        }
      }
      current_statement__ = 78;
      for (int j = 1; j <= N; ++j) {
        current_statement__ = 76;
        stan::model::assign(Likelihood, (se - (((se + sp) - 1) *
          stan::model::rvalue(P, "P",
            stan::model::index_uni(
              stan::model::rvalue(age, "age", stan::model::index_uni(j))),
            stan::model::index_uni(
              stan::model::rvalue(age_group, "age_group",
                stan::model::index_uni(j))),
            stan::model::index_uni(
              stan::model::rvalue(categoryindex, "categoryindex",
                stan::model::index_uni(j)))))),
          "assigning variable Likelihood", stan::model::index_uni(j));
      }
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "P1", P1, 0);
      current_statement__ = 6;
      stan::math::check_less_or_equal(function__, "P1", P1, 1);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "P", P, 0);
      current_statement__ = 7;
      stan::math::check_less_or_equal(function__, "P", P, 1);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "Flambda", Flambda, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "Likelihood",
        Likelihood, 0);
      current_statement__ = 9;
      stan::math::check_less_or_equal(function__, "Likelihood", Likelihood, 1);
      {
        current_statement__ = 81;
        for (int j = 1; j <= NGroups; ++j) {
          current_statement__ = 79;
          lp_accum__.add(stan::math::uniform_lpdf<propto__>(
                           stan::model::rvalue(lambda, "lambda",
                             stan::model::index_uni(j)), priorY1, priorY2));
        }
        current_statement__ = 86;
        for (int I = 1; I <= Ncategoryclass; ++I) {
          current_statement__ = 84;
          for (int i = 1; i <= maxNcategory; ++i) {
            current_statement__ = 82;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(
                             stan::model::rvalue(Flambda2, "Flambda2",
                               stan::model::index_uni(i),
                               stan::model::index_uni(I)), 0, 1.73));
          }
        }
        current_statement__ = 87;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(rho, priorRho));
        current_statement__ = 90;
        for (int j = 1; j <= N; ++j) {
          current_statement__ = 88;
          lp_accum__.add(stan::math::bernoulli_lpmf<false>(
                           stan::model::rvalue(Y, "Y",
                             stan::model::index_uni(j)),
                           stan::model::rvalue(Likelihood, "Likelihood",
                             stan::model::index_uni(j))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_independent_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<double> lambda =
        std::vector<double>(NGroups,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      lambda = in__.template read_constrain_lb<std::vector<local_scalar_t__>,
                 jacobian__>(0, lp__, NGroups);
      double rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      rho = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              20, lp__);
      std::vector<std::vector<double>> Flambda2 =
        std::vector<std::vector<double>>(maxNcategory,
          std::vector<double>(Ncategoryclass,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 3;
      Flambda2 = in__.template read<
                   std::vector<std::vector<local_scalar_t__>>>(maxNcategory,
                   Ncategoryclass);
      std::vector<double> x =
        std::vector<double>(A, std::numeric_limits<double>::quiet_NaN());
      double L = std::numeric_limits<double>::quiet_NaN();
      std::vector<std::vector<std::vector<double>>> P1 =
        std::vector<std::vector<std::vector<double>>>(A,
          std::vector<std::vector<double>>(NAgeGroups,
            std::vector<double>(Ncategory,
              std::numeric_limits<double>::quiet_NaN())));
      std::vector<std::vector<std::vector<double>>> P =
        std::vector<std::vector<std::vector<double>>>(A,
          std::vector<std::vector<double>>(NAgeGroups,
            std::vector<double>(Ncategory,
              std::numeric_limits<double>::quiet_NaN())));
      std::vector<double> Flambda =
        std::vector<double>(Ncategory,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<double> Likelihood =
        std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      double c = std::numeric_limits<double>::quiet_NaN();
      out__.write(lambda);
      out__.write(rho);
      for (int sym1__ = 1; sym1__ <= Ncategoryclass; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= maxNcategory; ++sym2__) {
          out__.write(Flambda2[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 11;
      c = 0;
      current_statement__ = 26;
      if (stan::math::logical_negation(cat_lambda)) {
        current_statement__ = 24;
        for (int i = 1; i <= Ncategory; ++i) {
          current_statement__ = 22;
          stan::model::assign(Flambda, 1, "assigning variable Flambda",
            stan::model::index_uni(i));
        }
      } else {
        current_statement__ = 20;
        for (int i = 1; i <= Ncategory; ++i) {
          current_statement__ = 12;
          c = 0;
          current_statement__ = 17;
          for (int I = 1; I <= Ncategoryclass; ++I) {
            current_statement__ = 15;
            if (stan::math::logical_gt(
                  stan::model::rvalue(MatrixCategory, "MatrixCategory",
                    stan::model::index_uni(i), stan::model::index_uni(I)), 1)) {
              current_statement__ = 13;
              c = (c +
                stan::model::rvalue(Flambda2, "Flambda2",
                  stan::model::index_uni(
                    stan::model::rvalue(MatrixCategory, "MatrixCategory",
                      stan::model::index_uni(i), stan::model::index_uni(I))),
                  stan::model::index_uni(I)));
            }
          }
          current_statement__ = 18;
          stan::model::assign(Flambda, stan::math::exp(c),
            "assigning variable Flambda", stan::model::index_uni(i));
        }
      }
      current_statement__ = 27;
      L = 1;
      current_statement__ = 43;
      if (stan::math::logical_eq(seroreversion, 0)) {
        current_statement__ = 41;
        for (int J = 1; J <= NAgeGroups; ++J) {
          current_statement__ = 39;
          for (int i = 1; i <= Ncategory; ++i) {
            current_statement__ = 28;
            stan::model::assign(P1,
              stan::math::exp(
                (-stan::model::rvalue(Flambda, "Flambda",
                    stan::model::index_uni(i)) *
                stan::model::rvalue(lambda, "lambda",
                  stan::model::index_uni(1)))), "assigning variable P1",
              stan::model::index_uni(1), stan::model::index_uni(J),
              stan::model::index_uni(i));
            current_statement__ = 36;
            for (int j = 1; j <= (A - 1); ++j) {
              current_statement__ = 29;
              stan::model::assign(x, 1, "assigning variable x",
                stan::model::index_uni(j));
              current_statement__ = 34;
              if (stan::math::logical_lt(j,
                    stan::model::rvalue(age_at_init, "age_at_init",
                      stan::model::index_uni(J)))) {
                current_statement__ = 32;
                stan::model::assign(P1,
                  stan::math::exp(
                    (-stan::model::rvalue(Flambda, "Flambda",
                        stan::model::index_uni(i)) *
                    stan::model::rvalue(lambda, "lambda",
                      stan::model::index_uni(j)))), "assigning variable P1",
                  stan::model::index_uni((j + 1)), stan::model::index_uni(J),
                  stan::model::index_uni(i));
              } else {
                current_statement__ = 30;
                stan::model::assign(P1,
                  (stan::model::rvalue(P1, "P1", stan::model::index_uni(j),
                     stan::model::index_uni(J), stan::model::index_uni(i)) *
                  stan::math::exp(
                    (-stan::model::rvalue(Flambda, "Flambda",
                        stan::model::index_uni(i)) *
                    stan::model::rvalue(lambda, "lambda",
                      stan::model::index_uni((j + 1)))))),
                  "assigning variable P1", stan::model::index_uni((j + 1)),
                  stan::model::index_uni(J), stan::model::index_uni(i));
              }
            }
            current_statement__ = 37;
            stan::model::assign(x, 1, "assigning variable x",
              stan::model::index_uni(A));
          }
        }
      }
      current_statement__ = 64;
      if (stan::math::logical_eq(seroreversion, 1)) {
        current_statement__ = 62;
        for (int J = 1; J <= NAgeGroups; ++J) {
          current_statement__ = 60;
          for (int i = 1; i <= Ncategory; ++i) {
            current_statement__ = 44;
            stan::model::assign(x, 1, "assigning variable x",
              stan::model::index_uni(A));
            current_statement__ = 47;
            for (int j = 1; j <= A; ++j) {
              current_statement__ = 45;
              stan::model::assign(x,
                stan::math::exp(
                  (-stan::model::rvalue(Flambda, "Flambda",
                      stan::model::index_uni(i)) *
                  stan::model::rvalue(lambda, "lambda",
                    stan::model::index_uni(1)))), "assigning variable x",
                stan::model::index_uni(j));
            }
            current_statement__ = 58;
            for (int j = 1; j <= A; ++j) {
              current_statement__ = 48;
              L = (stan::model::rvalue(Flambda, "Flambda",
                     stan::model::index_uni(i))
                *
                stan::model::rvalue(lambda, "lambda",
                  stan::model::index_uni(
                    stan::model::rvalue(age_at_init, "age_at_init",
                      stan::model::index_uni(J)))));
              current_statement__ = 49;
              stan::model::assign(x, ((rho / (L + rho)) + ((L / (L + rho)) *
                stan::math::exp(-L))), "assigning variable x",
                stan::model::index_uni(j));
              current_statement__ = 55;
              if (stan::math::logical_gt(j, 1)) {
                current_statement__ = 53;
                for (int k = 2; k <= j; ++k) {
                  current_statement__ = 50;
                  L = (stan::model::rvalue(Flambda, "Flambda",
                         stan::model::index_uni(i))
                    *
                    stan::model::rvalue(lambda, "lambda",
                      stan::model::index_uni(((j - k) + 2))));
                  current_statement__ = 51;
                  stan::model::assign(x,
                    ((stan::model::rvalue(x, "x",
                        stan::model::index_uni(((j - k) + 2))) *
                    stan::math::exp(-(rho + L))) + ((rho / (L + rho)) * (1 -
                    stan::math::exp(-(rho + L))))), "assigning variable x",
                    stan::model::index_uni((((j - k) + 2) - 1)));
                }
              }
              current_statement__ = 56;
              stan::model::assign(P1,
                stan::model::rvalue(x, "x",
                  stan::model::index_uni(
                    stan::model::rvalue(age_at_init, "age_at_init",
                      stan::model::index_uni(J)))), "assigning variable P1",
                stan::model::index_uni(j), stan::model::index_uni(J),
                stan::model::index_uni(i));
            }
          }
        }
      }
      current_statement__ = 75;
      for (int J = 1; J <= NAgeGroups; ++J) {
        current_statement__ = 73;
        for (int i = 1; i <= Ncategory; ++i) {
          current_statement__ = 71;
          for (int j = 1; j <= A; ++j) {
            current_statement__ = 65;
            stan::model::assign(P, 0, "assigning variable P",
              stan::model::index_uni(j), stan::model::index_uni(J),
              stan::model::index_uni(i));
            current_statement__ = 68;
            for (int k =
                   stan::model::rvalue(class1, "class1",
                     stan::model::index_uni(j), stan::model::index_uni(J)); k
                 <=
                 stan::model::rvalue(class2, "class2",
                   stan::model::index_uni(j), stan::model::index_uni(J)); ++k) {
              current_statement__ = 66;
              stan::model::assign(P,
                (stan::model::rvalue(P1, "P1", stan::model::index_uni(k),
                   stan::model::index_uni(J), stan::model::index_uni(i)) +
                stan::model::rvalue(P, "P", stan::model::index_uni(j),
                  stan::model::index_uni(J), stan::model::index_uni(i))),
                "assigning variable P", stan::model::index_uni(j),
                stan::model::index_uni(J), stan::model::index_uni(i));
            }
            current_statement__ = 69;
            stan::model::assign(P,
              (stan::model::rvalue(P, "P", stan::model::index_uni(j),
                 stan::model::index_uni(J), stan::model::index_uni(i)) /
              ((stan::model::rvalue(class2, "class2",
                  stan::model::index_uni(j), stan::model::index_uni(J)) -
              stan::model::rvalue(class1, "class1",
                stan::model::index_uni(j), stan::model::index_uni(J))) + 1)),
              "assigning variable P", stan::model::index_uni(j),
              stan::model::index_uni(J), stan::model::index_uni(i));
          }
        }
      }
      current_statement__ = 78;
      for (int j = 1; j <= N; ++j) {
        current_statement__ = 76;
        stan::model::assign(Likelihood, (se - (((se + sp) - 1) *
          stan::model::rvalue(P, "P",
            stan::model::index_uni(
              stan::model::rvalue(age, "age", stan::model::index_uni(j))),
            stan::model::index_uni(
              stan::model::rvalue(age_group, "age_group",
                stan::model::index_uni(j))),
            stan::model::index_uni(
              stan::model::rvalue(categoryindex, "categoryindex",
                stan::model::index_uni(j)))))),
          "assigning variable Likelihood", stan::model::index_uni(j));
      }
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "P1", P1, 0);
      current_statement__ = 6;
      stan::math::check_less_or_equal(function__, "P1", P1, 1);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "P", P, 0);
      current_statement__ = 7;
      stan::math::check_less_or_equal(function__, "P", P, 1);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "Flambda", Flambda, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "Likelihood",
        Likelihood, 0);
      current_statement__ = 9;
      stan::math::check_less_or_equal(function__, "Likelihood", Likelihood, 1);
      if (emit_transformed_parameters__) {
        out__.write(x);
        out__.write(L);
        for (int sym1__ = 1; sym1__ <= Ncategory; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= NAgeGroups; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= A; ++sym3__) {
              out__.write(P1[(sym3__ - 1)][(sym2__ - 1)][(sym1__ - 1)]);
            }
          }
        }
        for (int sym1__ = 1; sym1__ <= Ncategory; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= NAgeGroups; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= A; ++sym3__) {
              out__.write(P[(sym3__ - 1)][(sym2__ - 1)][(sym1__ - 1)]);
            }
          }
        }
        out__.write(Flambda);
        out__.write(Likelihood);
        out__.write(c);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<local_scalar_t__> lambda =
        std::vector<local_scalar_t__>(NGroups, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(lambda,
        in__.read<std::vector<local_scalar_t__>>(NGroups),
        "assigning variable lambda");
      out__.write_free_lb(0, lambda);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 2;
      rho = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 20, rho);
      std::vector<std::vector<local_scalar_t__>> Flambda2 =
        std::vector<std::vector<local_scalar_t__>>(maxNcategory,
          std::vector<local_scalar_t__>(Ncategoryclass, DUMMY_VAR__));
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= Ncategoryclass; ++sym1__) {
        current_statement__ = 3;
        for (int sym2__ = 1; sym2__ <= maxNcategory; ++sym2__) {
          current_statement__ = 3;
          Flambda2[(sym2__ - 1)][(sym1__ -
            1)] = in__.read<local_scalar_t__>();
        }
      }
      out__.write(Flambda2);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "lambda", "double",
        std::vector<size_t>{static_cast<size_t>(NGroups)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "rho", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "Flambda2",
        "double",
        std::vector<size_t>{static_cast<size_t>(maxNcategory),
          static_cast<size_t>(Ncategoryclass)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<local_scalar_t__> lambda =
        std::vector<local_scalar_t__>(NGroups, DUMMY_VAR__);
      current_statement__ = 1;
      lambda = context__.vals_r("lambda");
      out__.write_free_lb(0, lambda);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 2;
      rho = context__.vals_r("rho")[(1 - 1)];
      out__.write_free_lub(0, 20, rho);
      std::vector<std::vector<local_scalar_t__>> Flambda2 =
        std::vector<std::vector<local_scalar_t__>>(maxNcategory,
          std::vector<local_scalar_t__>(Ncategoryclass, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> Flambda2_flat__;
        current_statement__ = 3;
        Flambda2_flat__ = context__.vals_r("Flambda2");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= Ncategoryclass; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= maxNcategory; ++sym2__) {
            current_statement__ = 3;
            stan::model::assign(Flambda2, Flambda2_flat__[(pos__ - 1)],
              "assigning variable Flambda2", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 3;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(Flambda2);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"lambda", "rho", "Flambda2"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"x", "L", "P1", "P", "Flambda", "Likelihood", "c"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    NGroups)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(maxNcategory),
                  static_cast<size_t>(Ncategoryclass)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(A)},
             std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(A),
               static_cast<size_t>(NAgeGroups),
               static_cast<size_t>(Ncategory)},
             std::vector<size_t>{static_cast<size_t>(A),
               static_cast<size_t>(NAgeGroups),
               static_cast<size_t>(Ncategory)},
             std::vector<size_t>{static_cast<size_t>(Ncategory)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= NGroups; ++sym1__) {
      param_names__.emplace_back(std::string() + "lambda" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= Ncategoryclass; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= maxNcategory; ++sym2__) {
        param_names__.emplace_back(std::string() + "Flambda2" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= A; ++sym1__) {
        param_names__.emplace_back(std::string() + "x" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "L");
      for (int sym1__ = 1; sym1__ <= Ncategory; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= NAgeGroups; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= A; ++sym3__) {
            param_names__.emplace_back(std::string() + "P1" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= Ncategory; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= NAgeGroups; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= A; ++sym3__) {
            param_names__.emplace_back(std::string() + "P" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= Ncategory; ++sym1__) {
        param_names__.emplace_back(std::string() + "Flambda" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "Likelihood" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "c");
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= NGroups; ++sym1__) {
      param_names__.emplace_back(std::string() + "lambda" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= Ncategoryclass; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= maxNcategory; ++sym2__) {
        param_names__.emplace_back(std::string() + "Flambda2" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= A; ++sym1__) {
        param_names__.emplace_back(std::string() + "x" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "L");
      for (int sym1__ = 1; sym1__ <= Ncategory; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= NAgeGroups; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= A; ++sym3__) {
            param_names__.emplace_back(std::string() + "P1" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= Ncategory; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= NAgeGroups; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= A; ++sym3__) {
            param_names__.emplace_back(std::string() + "P" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= Ncategory; ++sym1__) {
        param_names__.emplace_back(std::string() + "Flambda" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "Likelihood" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "c");
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"lambda\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NGroups) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"Flambda2\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(maxNcategory) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(Ncategoryclass) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"x\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(A) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"L\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"P1\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(A) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(NAgeGroups) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(Ncategory) + ",\"element_type\":{\"name\":\"real\"}}}},\"block\":\"transformed_parameters\"},{\"name\":\"P\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(A) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(NAgeGroups) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(Ncategory) + ",\"element_type\":{\"name\":\"real\"}}}},\"block\":\"transformed_parameters\"},{\"name\":\"Flambda\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Ncategory) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"Likelihood\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"lambda\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NGroups) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"Flambda2\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(maxNcategory) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(Ncategoryclass) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"x\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(A) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"L\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"P1\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(A) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(NAgeGroups) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(Ncategory) + ",\"element_type\":{\"name\":\"real\"}}}},\"block\":\"transformed_parameters\"},{\"name\":\"P\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(A) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(NAgeGroups) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(Ncategory) + ",\"element_type\":{\"name\":\"real\"}}}},\"block\":\"transformed_parameters\"},{\"name\":\"Flambda\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Ncategory) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"Likelihood\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((NGroups + 1) + (maxNcategory *
      Ncategoryclass));
    const size_t num_transformed = emit_transformed_parameters * (((((((A +
      1) + ((A * NAgeGroups) * Ncategory)) + ((A * NAgeGroups) * Ncategory))
      + Ncategory) + N) + 1));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((NGroups + 1) + (maxNcategory *
      Ncategoryclass));
    const size_t num_transformed = emit_transformed_parameters * (((((((A +
      1) + ((A * NAgeGroups) * Ncategory)) + ((A * NAgeGroups) * Ncategory))
      + Ncategory) + N) + 1));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_independent_namespace::model_independent;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_independent_namespace::profiles__;
}
#endif
#endif
