.onLoad <- function(libname, pkgname) {
  # Find the stanmodels object inside your package namespace, safely
  ns <- asNamespace(pkgname)
  if (!exists("stanmodels", envir = ns, inherits = FALSE)) {
    return(invisible())
  }
  sm <- get("stanmodels", envir = ns)
  
  # Build the C++ module names generated by rstan/rstantools
  modules <- paste0("stan_fit4", names(sm), "_mod")
  
  # Load each module; be robust to missing/failed ones
  for (mod in modules) {
    tryCatch(
      Rcpp::loadModule(mod, what = TRUE),
      error = function(e) {
        packageStartupMessage(
          sprintf("Rcpp module failed to load: %s (%s)", mod, conditionMessage(e))
        )
      }
    )
  }
  invisible()
}